// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleType is the golang structure of table article_type for DAO operations like Where/Data.
type ArticleType struct {
	g.Meta    `orm:"table:article_type, do:true"`
	Id        interface{} //
	Name      interface{} // 分类名称
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
