// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/internal/dao/internal"
)

// internalArticleTypeDao is internal type for wrapping internal DAO implements.
type internalArticleTypeDao = *internal.ArticleTypeDao

// articleTypeDao is the data access object for table article_type.
// You can define custom methods on it to extend its functionality as you wish.
type articleTypeDao struct {
	internalArticleTypeDao
}

var (
	// ArticleType is globally public accessible object for table article_type operations.
	ArticleType = articleTypeDao{
		internal.NewArticleTypeDao(),
	}
)

// Fill with you ideas below.
