// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/internal/dao/internal"
)

// internalRoleApiDao is internal type for wrapping internal DAO implements.
type internalRoleApiDao = *internal.RoleApiDao

// roleApiDao is the data access object for table role_api.
// You can define custom methods on it to extend its functionality as you wish.
type roleApiDao struct {
	internalRoleApiDao
}

var (
	// RoleApi is globally public accessible object for table role_api operations.
	RoleApi = roleApiDao{
		internal.NewRoleApiDao(),
	}
)

// Fill with you ideas below.
