// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminRole is the golang structure for table admin_role.
type AdminRole struct {
	AdminId int `json:"adminId" description:""`
	RoleId  int `json:"roleId"  description:""`
}
