// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure for table api.
type Api struct {
	Id        int         `json:"id"        description:""`
	Meun      string      `json:"meun"      description:"菜单地址"`
	Name      string      `json:"name"      description:"名称"`
	Key       string      `json:"key"       description:"标识"`
	Path      string      `json:"path"      description:"请求地址"`
	Method    int         `json:"method"    description:"请求类型"`
	Type      int         `json:"type"      description:"菜单类型"`
	Pid       int         `json:"pid"       description:"上级ID"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
