// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	Id        int         `json:"id"        description:""`
	Name      string      `json:"name"      description:"文章名称"`
	TypeId    int         `json:"typeId"    description:"文章分类ID"`
	Content   string      `json:"content"   description:"内容路径"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
