// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleApi is the golang structure for table role_api.
type RoleApi struct {
	RoleId int `json:"roleId" description:""`
	ApiId  int `json:"apiId"  description:""`
}
